version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing frontend dependencies...
      - npm install

  build:
    commands:
      - echo Building the frontend project...
      - npm run build
      - echo Running SonarCloud analysis...
      - sonar-scanner -Dsonar.projectKey=devsecops221_devsecops -Dsonar.organization=devsecops221 -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$SONAR_TOKEN

artifacts:
  files:
    - '**/*'
  base-directory: build
