version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd frontend
      - npm install
  build:
    commands:
      - npm run build
      - docker build -t frontend-repo .
      - docker tag frontend-repo:latest 542267705220.dkr.ecr.us-east-1.amazonaws.com/frontend-repo:latest
  post_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 542267705220.dkr.ecr.us-east-1.amazonaws.com
      - docker push 542267705220.dkr.ecr.us-east-1.amazonaws.com/frontend-repo:latest
      - cd ..
      - printf '[{"name":"frontend","imageUri":"542267705220.dkr.ecr.us-east-1.amazonaws.com/frontend-repo:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
