version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - cd backend
      - ./mvnw clean install
  build:
    commands:
      - docker build -t backend-repo ./backend
      - docker tag backend-repo:latest <your-id>.dkr.ecr.us-east-1.amazonaws.com/backend-repo:latest
  post_build:
    commands:
      - docker push 542267705220.dkr.ecr.us-east-1.amazonaws.com/backend-repo:latest
