version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - cd backend                     # move into backend folder
      - chmod +x mvnw                  # give executable permission to mvnw
      - ./mvnw clean install           # build springboot project
      - ./mvnw org.owasp:dependency-check-maven:check
      - curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006.zip
      - unzip sonar-scanner.zip
      - export PATH=$PATH:$(pwd)/sonar-scanner-5.0.1.3006/bin

  build:
    commands:
      - docker build -t backend-repo . # build docker image
      - docker tag backend-repo:latest 542267705220.dkr.ecr.us-east-1.amazonaws.com/backend-repo:latest

  post_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 542267705220.dkr.ecr.us-east-1.amazonaws.com
      - docker push 542267705220.dkr.ecr.us-east-1.amazonaws.com/backend-repo:latest
      - cd ..
      - printf '[{"name":"backend","imageUri":"542267705220.dkr.ecr.us-east-1.amazonaws.com/backend-repo:latest"}]' > imagedefinitions.json
      - echo Running SonarCloud Scan...
      - |
        sonar-scanner \
          -Dsonar.projectKey=devsecops221_backend \
          -Dsonar.organization=devsecops221 \
          -Dsonar.sources=backend/src/main/java \
          -Dsonar.java.binaries=backend/target \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=$SONAR_TOKEN

artifacts:
  files:
    - imagedefinitions.json
