version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - cd backend                     # move into backend folder
      - chmod +x mvnw                  # give executable permission to mvnw
      - ./mvnw clean install           # build springboot project

  build:
    commands:
      - docker build -t backend-repo . # build docker image
      - docker tag backend-repo:latest 542267705220.dkr.ecr.us-east-1.amazonaws.com/backend-repo:latest

  post_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 542267705220.dkr.ecr.us-east-1.amazonaws.com
      - docker push 542267705220.dkr.ecr.us-east-1.amazonaws.com/backend-repo:latest
